"""FlaskVerseHub application factory.

``create_app`` wires configuration, extensions, blueprints, error handling,
observability and CLI commands. Blueprints are registered from a single
declarative table so the URL map is visible at a glance.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from flask import Flask
from sqlalchemy.pool import StaticPool

from app.config import Config, get_config
from app.extensions import (
    cache,
    cors,
    csrf,
    db,
    jwt,
    limiter,
    login_manager,
    mail,
    migrate,
    socketio,
)

__version__ = Config.APP_VERSION


def create_app(config_name: str | None = None, overrides: dict[str, Any] | None = None) -> Flask:
    """Build a configured :class:`flask.Flask` instance.

    ``config_name`` selects a profile from :data:`app.config.CONFIGS`;
    ``overrides`` are applied last and are intended for tests.
    """
    app = Flask(__name__, instance_relative_config=True)
    config_class = get_config(config_name)
    app.config.from_object(config_class)
    if overrides:
        app.config.update(overrides)
    config_class.init_app(app)
    Path(app.instance_path).mkdir(parents=True, exist_ok=True)

    _init_extensions(app)
    _register_blueprints(app)
    _register_infrastructure(app)
    _register_template_helpers(app)
    _register_shell_context(app)
    return app


def _init_extensions(app: Flask) -> None:
    uri = str(app.config.get("SQLALCHEMY_DATABASE_URI", ""))
    options = dict(app.config.get("SQLALCHEMY_ENGINE_OPTIONS") or {})
    if uri in {"sqlite://", "sqlite:///:memory:"}:
        # One shared in-memory database for the whole process (tests).
        options["poolclass"] = StaticPool
        options.setdefault("connect_args", {"check_same_thread": False})
    options = {k: v for k, v in options.items() if v is not None}
    app.config["SQLALCHEMY_ENGINE_OPTIONS"] = options

    db.init_app(app)
    migrate.init_app(
        app,
        db,
        directory=str(Path(app.root_path).parent / "migrations"),
        render_as_batch=True,  # SQLite needs batch mode for ALTER TABLE
        render_item=_render_migration_item,
    )
    login_manager.init_app(app)
    cache.init_app(app)
    mail.init_app(app)
    jwt.init_app(app)
    csrf.init_app(app)
    limiter.init_app(app)
    cors.init_app(
        app,
        resources={r"/api/*": {"origins": app.config.get("CORS_ORIGINS", "*")}},
        supports_credentials=False,
    )
    socketio.init_app(
        app,
        async_mode=app.config.get("SOCKETIO_ASYNC_MODE", "threading"),
        cors_allowed_origins=app.config.get("SOCKETIO_CORS_ALLOWED_ORIGINS", "*"),
        message_queue=app.config.get("SOCKETIO_MESSAGE_QUEUE"),
        logger=False,
        engineio_logger=False,
    )

    login_manager.login_view = "auth.login"
    login_manager.login_message = "Please sign in to access this page."
    login_manager.login_message_category = "info"
    login_manager.session_protection = app.config.get("SESSION_PROTECTION", "strong")

    @login_manager.user_loader
    def _load_user(user_id: str) -> Any:
        from app.models import User

        return db.session.get(User, int(user_id))


def _render_migration_item(type_: str, obj: Any, _autogen_context: Any) -> str | bool:
    """Render custom column types in autogenerated migrations as plain SQLAlchemy types."""
    from app.models import UTCDateTime

    if type_ == "type" and isinstance(obj, UTCDateTime):
        return "sa.DateTime()"
    return False


def _register_blueprints(app: Flask) -> None:
    from app.api_hub import bp as api_bp
    from app.auth import bp as auth_bp
    from app.dashboard import bp as dashboard_bp
    from app.knowledge_vault import bp as vault_bp
    from app.main import bp as main_bp

    app.register_blueprint(main_bp)
    app.register_blueprint(auth_bp, url_prefix="/auth")
    app.register_blueprint(vault_bp, url_prefix="/knowledge")
    app.register_blueprint(api_bp, url_prefix="/api/v1")
    app.register_blueprint(dashboard_bp, url_prefix="/dashboard")


def _register_infrastructure(app: Flask) -> None:
    from app import observability
    from app.cli import register_cli
    from app.errors import register_error_handlers
    from app.search import service as search_service
    from app.security import register_security_headers

    observability.init_app(app)
    search_service.init_app(app)
    register_error_handlers(app)
    register_security_headers(app)
    register_cli(app)


def _register_template_helpers(app: Flask) -> None:
    from app.utils.text import excerpt
    from app.utils.time import humanize_delta, utcnow

    @app.template_filter("timeago")
    def _timeago(value: Any) -> str:
        return humanize_delta(value)

    @app.template_filter("datetime")
    def _datetime(value: Any, fmt: str = "%Y-%m-%d %H:%M UTC") -> str:
        return value.strftime(fmt) if value else ""

    @app.template_filter("excerpt")
    def _excerpt(value: Any, length: int = 200) -> str:
        return excerpt(value, length=length)

    @app.template_filter("reject_key")
    def _reject_key(mapping: dict[str, Any], key: str) -> dict[str, Any]:
        return {k: v for k, v in mapping.items() if k != key}

    import platform
    from importlib import metadata

    flask_version = metadata.version("flask")
    python_version = platform.python_version()
    endpoints: set[str] = set()

    @app.context_processor
    def _inject_globals() -> dict[str, Any]:
        from flask_login import current_user

        if not endpoints:
            endpoints.update(rule.endpoint for rule in app.url_map.iter_rules())
        unread = 0
        if current_user.is_authenticated:
            from app.services.notifications import unread_count

            unread = unread_count(current_user)
        return {
            "unread_notifications": unread,
            "app_name": app.config.get("APP_NAME"),
            "app_version": app.config.get("APP_VERSION"),
            "flask_version": flask_version,
            "python_version": python_version,
            "url_map_endpoints": endpoints,
            "now": utcnow(),
        }


def _register_shell_context(app: Flask) -> None:
    @app.shell_context_processor
    def _shell_context() -> dict[str, Any]:
        from app import models

        return {"db": db, **{name: getattr(models, name) for name in models.__all__}}


__all__ = ["__version__", "create_app"]
